### ISSUE TITLE
BuildCraft Pipes don't fully interact with TFC Barrels

### ISSUE THREAD

**Issue by RandomIntel** [Shurgent/TFCTech#14]
Extraction of items works. Placing items into barrels does not. Fluid pipes don't even connect to Barrels.

I debated whether to post this as a bug, because I'm not sure is this is just a planned feature.

**Comment by Shurgent** [comment]
Hi!
Unfortunately, Buildcraft pipes are not compatible with Barrels. I did not plan to make possible a direct connection to the Barrels, because there are problems with switching liquid / items modes, etc.. I'm planned to add some lid for the barrel, which will be connecting to pipes. But for now, you can use BC tanks to store liquids and chests for items.

**Comment by RandomIntel** [comment]
Ok, got it! The idea of having an interface block between the barrel and the pipe is actually kind of cool. Thanks for all of this, by the way.
