### ISSUE TITLE
Startup crash with buildcraft

### ISSUE THREAD

**Issue by wormzjl** [Shurgent/TFCTech#15]
http://pastebin.com/Pqq9FZHt
Probably because that I have only used a few modules from buildcraft, but without robotics and transportation
Could you add some detection for individual bc modules?

**Comment by Shurgent** [comment]
It's strange, because I have added detection of the individual modules:
https://github.com/Shurgent/TFCTech/blob/master/src/main/java/ua/pp/shurgent/tfctech/TFCTech.java#L97
https://github.com/Shurgent/TFCTech/blob/master/src/main/java/ua/pp/shurgent/tfctech/integration/bc/TFCTechBCRecipes.java#L89
I do not understand why this is happening.
I'll try to spread the processing of recipes from different modules in separate classes. Maybe this will help.

**Comment by Shurgent** [comment]
Fixed in 0.2.10-A15 (I hope so)
